#! /bin/bash
read -r -p "Are you sure? [Y/n] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
	echo "----------------------------------------------------"
	echo "Building production assets...";
	echo "----------------------------------------------------"
	npm run build-prod
	echo " "
	echo " "
	echo "----------------------------------------------------"
    echo "Pushing files to emilylee.org...";
    echo "----------------------------------------------------"
	rsync -avH --delete --exclude '.idea' --exclude '.git' --exclude 'node_modules' --exclude 'npm-debug*' --exclude 'deploy' ./ root@138.197.26.22/:/var/www/html/
    echo "----------------------------------------------------"
    echo "Build complete. ^_^";
    echo "----------------------------------------------------"
else
	exit
fi