#! /bin/bash
read -r -p "Are you sure? [Y/n] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
	echo "----------------------------------------------------"
	echo "Building production assets...";
	echo "----------------------------------------------------"
	echo " "
	echo " "
	echo "----------------------------------------------------"
    echo "Pushing files to emilylee.org...";
    echo "----------------------------------------------------"
	rsync -avH --delete --exclude '.idea' --exclude '.git' ./ root@emilylee.org:/var/www/html/
    echo "----------------------------------------------------"
    echo "Build complete. ^_^";
    echo "----------------------------------------------------"
else
	exit
fi